version: "3.8"

services:
  app:
    build:
      context: .
      target: development # 開発用ステージを使用
    container_name: myapp_dev
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=myapp_dev
      - GIN_MODE=debug
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
      - go_modules_cache:/go/pkg/mod
    working_dir: /app
    # go runで直接実行（ホットリロードなし）
    command: ["go", "run", "main.go"]

  db:
    image: postgres:15-alpine
    container_name: myapp_db_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d myapp_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data:
  go_modules_cache:
